import sys
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import firwin

def generate(filter_depth, data_width, cutoff_freq, sample_rate):
    # Design the FIR filter with the given parameters
    fir_coefficients = firwin(filter_depth, cutoff_freq, fs=sample_rate, pass_zero=True)
    
    # Quantize coefficients based on data width
    max_val = 2**(data_width - 1) - 1
    quantized_coefficients = np.round(fir_coefficients * max_val).astype(int)

    # Ensure coefficients fit within the data width by clipping
    quantized_coefficients = np.clip(quantized_coefficients, -max_val, max_val)

    # for c in fir_coefficients:
    #     print(c)
    # for c in quantized_coefficients:
    #     print(c);

    return quantized_coefficients


def plot(weights):
    plt.figure(figsize=(10, 4))
    plt.stem(range(len(weights)), weights, basefmt=" ")
    plt.title("FIR Filter Weights")
    plt.xlabel("Weight Index")
    plt.ylabel("Amplitude")
    plt.grid(True)
    plt.savefig("weights.png")
    print("Fir filter weights plotted in weights.png")


def write_mem(weights, DATA_WIDTH):
    # Open the file to write weights in hexadecimal format
    with open("weights.mem", "w") as f:
        for i, weight in enumerate(weights):
            # Convert each weight to hexadecimal, keeping only the lower DATA_WIDTH bits
            hex_value = f"{(weight & ((1 << DATA_WIDTH) - 1)):0{DATA_WIDTH // 4}X}"
            f.write(f"@{i:02X} {hex_value}\n")
    print("FIR filter weights written to weights.mem in hexadecimal format.")


def write_verilog(weights, data_width):
    # Open a Verilog header file for writing
    with open("weights.vh", "w") as f:
        f.write("// FIR filter weights generated by Python\n")
        f.write(f"// wire signed [{data_width-1}:0] weights [{len(weights)-1}:0];\n\n")
        
        # Define each weight individually in hexadecimal format
        for i, weight in enumerate(weights):
            hex_value = f"{(weight & ((1 << data_width) - 1)):0{data_width // 4}X}"
            f.write(f"assign weights[{i}] = {data_width}'h{hex_value};\n")
    
    print("Verilog header generated as weights.vh.")


def main():

    # Parameters
    FILTER_DEPTH = 64 
    SAMPLE_RATE = 44000
    CUTOFF_FREQ = 1000

    DATA_WIDTH = 24          # Number of bits for each coefficient
    normalized_cutoff = CUTOFF_FREQ / (SAMPLE_RATE / 2)

    # Generate FIR filter weights
    weights = generate(FILTER_DEPTH, DATA_WIDTH, normalized_cutoff, SAMPLE_RATE)
    plot(weights)
    write_mem(weights, DATA_WIDTH)
    write_verilog(weights, DATA_WIDTH)

if __name__ == '__main__':
    main()
