// FIR filter weights generated by Python
// wire signed [23:0] weights [11:0];

assign weights[0] = 24'h01292C;
assign weights[1] = 24'h029A9B;
assign weights[2] = 24'h06B15F;
assign weights[3] = 24'h0CA840;
assign weights[4] = 24'h1297CF;
assign weights[5] = 24'h164ACB;
assign weights[6] = 24'h164ACB;
assign weights[7] = 24'h1297CF;
assign weights[8] = 24'h0CA840;
assign weights[9] = 24'h06B15F;
assign weights[10] = 24'h029A9B;
assign weights[11] = 24'h01292C;
